AppBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        title:
            type: string
            length: '255'
        description:
            type: text
        auteur:
            type: string
            length: '255'
            nullable: true

    # lier deux entités : ici article est lié à commentaire
    # et un article peut avoir plusieurs commentaires
    oneToMany:
        commentaires:
            targetEntity: Commentaire
            mappedBy: article

    lifecycleCallbacks: {  }
