AppBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        title:
            type: string
            length: '255'
        description:
            type: text

    # lier deux entités : ici article est lié à commentaire
    # et un article peut avoir plusieurs commentaires
    oneToMany:
        commentaires:
            targetEntity: Commentaire
            mappedBy: article
            cascade: ['all']

    manyToOne:
        user:
            targetEntity: User
            inversedBy: articles

    manyToMany:
        tags:
            targetEntity: Tag
            mappedBy: articles
            cascade: ['all']

    lifecycleCallbacks: {  }
